const { createServer } = require('node:http');
const { createHash } = require('node:crypto');
const next = require('next');
const { jwtVerify } = require('jose');
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handler = app.getRequestHandler();
const cookie = (header, name) => header?.split(';').map((v) => v.trim()).find((v) => v.startsWith(`${name}=`))?.slice(name.length + 1);
const frame = (value) => { const data = Buffer.from(value); const head = data.length < 126 ? Buffer.from([0x81, data.length]) : Buffer.from([0x81, 126, data.length >> 8, data.length & 255]); return Buffer.concat([head, data]); };
const subscribe = (userId, listener) => { const hub = globalThis.__singlerentsEventHub || new Map(); globalThis.__singlerentsEventHub = hub; const set = hub.get(userId) || new Set(); set.add(listener); hub.set(userId, set); return () => { set.delete(listener); if (!set.size) hub.delete(userId); }; };
app.prepare().then(() => { const server = createServer(handler); server.on('upgrade', async (req, socket) => { if (req.url?.split('?')[0] !== '/ws') return socket.destroy(); try { const token = cookie(req.headers.cookie, 'singlerents_session'); const { payload } = await jwtVerify(token, new TextEncoder().encode(process.env.JWT_SECRET)); const accept = createHash('sha1').update(`${req.headers['sec-websocket-key']}258EAFA5-E914-47DA-95CA-C5AB0DC85B11`).digest('base64'); socket.write(`HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${accept}\r\n\r\n`); const off = subscribe(payload.sub, (event, data) => socket.write(frame(JSON.stringify({ event, data })))); socket.on('close', off); socket.on('error', off); socket.write(frame(JSON.stringify({ event: 'connected', data: {} }))); } catch { socket.destroy(); } }); server.listen(process.env.PORT || 3000, () => console.log(`> Ready on http://localhost:${process.env.PORT || 3000}`)); });
